### ISSUE TITLE
Add a README

### ISSUE THREAD

**Issue by elroykanye** [osscameroon/tg-gamebot#3]
Write a descriptive and concise README file for this project to show users how they can:
- get started with this tool
- install this tool and its dependencies
- contribute to the code of this tool
- contact the developers and get help working with this tool

A readme template is available to ease this process [here](https://github.com/elroykanye/readme-template).

**Comment by andrew21-mch** [comment]
@elroykanye i think this issue should be closed, there exists a readme already 
what do you think

**Comment by elroykanye** [comment]
I think so too. Closing now! :) Thanks
